export const ADD_NEW_EMPLOYEE_PENDING = "ADD_NEW_EMPLOYEE_PENDING";
export const ADD_NEW_EMPLOYEE_SUCCESS = "ADD_NEW_EMPLOYEE_SUCCESS";
export const ADD_NEW_EMPLOYEE_FAIL = "ADD_NEW_EMPLOYEE_FAIL";

export const SEARCH_EMPLOYEE_PENDING = "SEARCH_EMPLOYEE_PENDING";
export const FILTER_EMPLOYEES_BY_VALUES = "FILTER_EMPLOYEES_BY_VALUES";
export const SEARCH_EMPLOYEE_FAIL = "SEARCH_EMPLOYEE_FAIL";

export const GET_PAGINATED_DATA = "GET_PAGINATED_DATA"
