export const ADD_NEW_EMPLOYEE_PENDING = "ADD_NEW_EMPLOYEE_PENDING";
export const ADD_NEW_EMPLOYEE_SUCCESS = "ADD_NEW_EMPLOYEE_SUCCESS";
export const ADD_NEW_EMPLOYEE_FAIL = "ADD_NEW_EMPLOYEE_FAIL";

export const SEARCH_EMPLOYEE_PENDING = "SEARCH_EMPLOYEE_PENDING";
export const SEARCH_EMPLOYEE_SUCCESS = "SEARCH_EMPLOYEE_SUCCESS";
export const SEARCH_EMPLOYEE_FAIL = "SEARCH_EMPLOYEE_FAIL";
